version: "3.3"
services:
    api:
        build: .
        ports:
            - "5000:5000"
        volumes:
            - .:/usr/src/flaskbookapi
    database:
        image: 'mongo'
        environment:
            - MONGO_INITDB_DATABASE=temperature-data
            - MONGO_INITDB_ROOT_USERNAME=temperature-root
            - MONGO_INITDB_ROOT_PASSWORD=sHFyBLZBd5yLhCDG2GIgvQ
        volumes:
            - ./init-mongo.js:/docker-entrypoint-initdb.d/init_mongo.js:ro 
            - ./mongo-volume:/data/db 
        user: "${UID}:${GID}"
        ports:
            - '21017-21019:21017-21019'

